### ISSUE TITLE
compile on linux

### ISSUE THREAD

**Issue by talltyler** [acristoffers/CEFSimpleSample#2]
> sh build-linux.sh
> Building CEFSimpleSample::Independent
> Building CEFSimpleSample::Linux
> Linking...
> ../CEFSimpleSample/CEF/Linux/lib/libcef_dll_wrapper.a: could not read symbols: File in wrong format
> collect2: ld returned 1 exit status
> Copying files around...
> mv: cannot stat `CEFSimpleSample': No such file or directory

**Comment by acristoffers** [comment]
Sorry for taking so long to answer, my email is, for some unknown reason, not showing github messages in the inbox, but archiving them right away. :(

I just cloned the project and compiled without problems (in an up-to-date Ubuntu).

Maybe that's a compiler compatibility problem. Have you tried with different compilers?
If you can get the cefclient to compile, you can try to use its binaries.
Just replace them in the CEF folder and see if it works.

Or you can try to re-clone. Maybe the file is corrupt.

**Comment by miguelcobain** [comment]
I too get `mv: cannot stat`CEFSimpleSample': No such file or directory` during the linking phase.

**Comment by acristoffers** [comment]
The `mv: cannot stat` problem occurs when the compilation fails.
See the first error on the screen to see what really happened.
talltyler problem was that it did not link against the static library for some unknown reason, but your problem can be something else.

**Comment by miguelcobain** [comment]
Thank you for your quick response!

Here is the complete output:

```
$ ./build-linux.sh 
Building CEFSimpleSample::Independent
Building CEFSimpleSample::Linux
Linking...
/usr/bin/ld: Warning: size of symbol `CefBase::~CefBase()' changed from 38 in ClientHandler.o to 30 in ../CEFSimpleSample/CEF/Linux/lib/libcef_dll_wrapper.a(browser_ctocpp.o)
/usr/bin/ld: Warning: size of symbol `CefStringBase<CefStringTraitsUTF16>::~CefStringBase()' changed from 38 in ClientHandler.o to 30 in ../CEFSimpleSample/CEF/Linux/lib/libcef_dll_wrapper.a(display_handler_cpptoc.o)
/usr/bin/ld: Warning: size of symbol `CefStructBase<CefWindowInfoTraits>::~CefStructBase()' changed from 38 in main.o to 30 in ../CEFSimpleSample/CEF/Linux/lib/libcef_dll_wrapper.a(life_span_handler_cpptoc.o)
/usr/bin/ld: Warning: size of symbol `CefStructBase<CefBrowserSettingsTraits>::~CefStructBase()' changed from 38 in main.o to 30 in ../CEFSimpleSample/CEF/Linux/lib/libcef_dll_wrapper.a(life_span_handler_cpptoc.o)
/usr/bin/ld: Warning: size of symbol `CefWindowInfo::~CefWindowInfo()' changed from 38 in main.o to 30 in ../CEFSimpleSample/CEF/Linux/lib/libcef_dll_wrapper.a(life_span_handler_cpptoc.o)
/usr/bin/ld: skipping incompatible ../CEFSimpleSample/CEF/Linux/lib/libcef.so when searching for -lcef
/usr/bin/ld: cannot find -lcef
collect2: ld returned 1 exit status
Copying files around...
mv: cannot stat `CEFSimpleSample': No such file or directory
```

Besides some warnings, i think the problem happens at `/usr/bin/ld: cannot find -lcef`.
Any idea why this happens?

I'm Running ElementaryOS 64bit (based on Ubuntu 12.04).

**Comment by acristoffers** [comment]
Your system is 64bit, but CEF is only available in 32bit. That's most probably the problem.

**Comment by miguelcobain** [comment]
Well, if you check here there are some Linux 64bit builds: http://cefbuilds.com/
Maybe we just need to update binaries?

I'm looking for some kind of "starter project" that would let me build in all platforms. Something I could just clone and build. Something like this repo. Do you happen to know anything like this?

**Comment by acristoffers** [comment]
There wasn't a 64bit when I started the project, and I'm not sure wheter it's use is recommended since the Windows and Mac versions are tagged as experimental. Even if you go 64bits on Linux, you will probably run into problems on Windows and/or Mac.

If you want to go 64bits anyway, just download the binaries and substitute they on the CEF folder.
There's no change needed on Linux. On Mac and Windows you will need to update the project settings to switch to 64bit code, as it currently enforces 32bit.

**Comment by miguelcobain** [comment]
Maybe https://github.com/adobe/brackets-shell is the way to go these days!
