### ISSUE TITLE
Xcode 5

### ISSUE THREAD

**Issue by ghost** [acristoffers/CEFSimpleSample#4]
Any chance to update this code to xcode 5? It won't run there. 

I've changed the compiler per these instructions: (at the bottom) http://stackoverflow.com/questions/17162975/unsupported-compiler-com-apple-compilers-llvmgcc42-xcode-5-dp

But now I get different errors (5): 

Undefined symbols for architecture i386:
  "std::_Rb_tree_decrement(std::_Rb_tree_node_base*)", referenced from:
      std::_Rb_tree<CefStringBase<CefStringTraitsUTF16>, std::pair<CefStringBase<CefStringTraitsUTF16> const, CefStringBase<CefStringTraitsUTF16> >, std::_Select1ststd::pair<CefStringBase<CefStringTraitsUTF16 const, CefStringBase<CefStringTraitsUTF16> > >, std::less<CefStringBase<CefStringTraitsUTF16> >, std::allocatorstd::pair<CefStringBase<CefStringTraitsUTF16 const, CefStringBase<CefStringTraitsUTF16> > > >::_M_insert_unique(std::pair<CefStringBase<CefStringTraitsUTF16> const, CefStringBase<CefStringTraitsUTF16> > const&) in libcef_dll_wrapper.a(transfer_util.o)

etc.

Any idea on how to fix? 

Thanks,
Wesley

**Comment by acristoffers** [comment]
Sorry for taking long. I thought I had resolved this :/

You can upgrade the project, but has to leave the Architecture stuff untouched, as CEF only supports i386 (32bit).
Then you have to set the project to use libstdc++ instead of libc++ to get rid of those errors.

Fixed in master.
