### ISSUE TITLE
Where does libcef.dylib come from?

### ISSUE THREAD

**Issue by pupeno** [acristoffers/CEFSimpleSample#5]
I notice that you have two library files on your project for Mac, one is libcef_dll_wrapper.a and the other one is libcef.dylib, where does libcef.dylib come from?

**Comment by acristoffers** [comment]
I just took it from the CEF site. It actually needs updating. I'll do it when I have time to download and test everything again. You can grab it from here if you prefer (same as I did) https://cefbuilds.com

Sorry for answering 20 days after, but sometimes GitHub does not send me an email when people open issues :(
